inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - software_version.gemspec

Naming/MethodName:
  Enabled: false
