inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rspec

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Exclude:
    - software_version.gemspec
